// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineHelpSystem.Data;

namespace OnlineHelpSystem.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineHelpSystem.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TAuId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AssignmentNumber");

                    b.HasIndex("CourseId");

                    b.HasIndex("TAuId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            AssignmentNumber = 1,
                            CourseId = "I4DAB",
                            TAuId = "au542413"
                        },
                        new
                        {
                            AssignmentNumber = 2,
                            CourseId = "I4SWD",
                            TAuId = "au531234"
                        },
                        new
                        {
                            AssignmentNumber = 3,
                            CourseId = "I3ISU",
                            TAuId = "au542341"
                        });
                });

            modelBuilder.Entity("OnlineHelpSystem.Models.Course", b =>
                {
                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = "I4DAB",
                            Name = "Databaser"
                        },
                        new
                        {
                            CourseId = "I3ISU",
                            Name = "Indlejret Softwareudvikling"
                        },
                        new
                        {
                            CourseId = "I4SWD",
                            Name = "Software Design2345"
                        });
                });

            modelBuilder.Entity("OnlineHelpSystem.Models.Exercise", b =>
                {
                    b.Property<string>("Lecture")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ExerciseNumber")
                        .HasColumnType("int");

                    b.Property<string>("AuId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HelpWhere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TAuId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Lecture", "ExerciseNumber");

                    b.HasIndex("AuId");

                    b.HasIndex("CourseId");

                    b.HasIndex("TAuId");

                    b.ToTable("Excercises");

                    b.HasData(
                        new
                        {
                            Lecture = "EF Core",
                            ExerciseNumber = 1,
                            AuId = "au135848",
                            CourseId = "I4DAB",
                            HelpWhere = "opg 2.4",
                            TAuId = "au542413"
                        },
                        new
                        {
                            Lecture = "Migrations",
                            ExerciseNumber = 2,
                            AuId = "au136427",
                            CourseId = "I4DAB",
                            HelpWhere = "opg 1",
                            TAuId = "au542413"
                        },
                        new
                        {
                            Lecture = "Oberserver Pattern",
                            ExerciseNumber = 3,
                            AuId = "au145532",
                            CourseId = "I4SWD",
                            HelpWhere = "opg 3.7",
                            TAuId = "au531234"
                        },
                        new
                        {
                            Lecture = "Umulig c++",
                            ExerciseNumber = 4,
                            AuId = "au963454",
                            CourseId = "I3ISU",
                            HelpWhere = "opg 42.4",
                            TAuId = "au542341"
                        });
                });

            modelBuilder.Entity("OnlineHelpSystem.Models.Student", b =>
                {
                    b.Property<string>("AuId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            AuId = "au135848",
                            Name = "Soeren Brostroem"
                        },
                        new
                        {
                            AuId = "au135333",
                            Name = "Hanne Lind"
                        },
                        new
                        {
                            AuId = "au145532",
                            Name = "Soeren Brahe"
                        },
                        new
                        {
                            AuId = "au136427",
                            Name = "Flemming Dalager"
                        },
                        new
                        {
                            AuId = "au963454",
                            Name = "Mogens Bech"
                        });
                });

            modelBuilder.Entity("OnlineHelpSystem.Models.StudentAssignment", b =>
                {
                    b.Property<string>("AuId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AssignmentNumber")
                        .HasColumnType("int");

                    b.HasKey("AuId", "AssignmentNumber");

                    b.HasIndex("AssignmentNumber");

                    b.ToTable("StudentAssignment");
                });

            modelBuilder.Entity("OnlineHelpSystem.Models.StudentCourse", b =>
                {
                    b.Property<string>("AuId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.HasKey("AuId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourse");
                });

            modelBuilder.Entity("OnlineHelpSystem.Models.Teacher", b =>
                {
                    b.Property<string>("TAuId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TAuId");

                    b.HasIndex("CourseId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TAuId = "au758313",
                            Name = "Lars Larsen"
                        },
                        new
                        {
                            TAuId = "au542341",
                            Name = "Barack Obama"
                        },
                        new
                        {
                            TAuId = "au542413",
                            Name = "Joe Exotic"
                        },
                        new
                        {
                            TAuId = "au531234",
                            Name = "Saul Goodman"
                        },
                        new
                        {
                            TAuId = "au1241245",
                            Name = "Phoebe Buffay"
                        });
                });

            modelBuilder.Entity("OnlineHelpSystem.Models.Assignment", b =>
                {
                    b.HasOne("OnlineHelpSystem.Models.Course", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseId");

                    b.HasOne("OnlineHelpSystem.Models.Teacher", "Teacher")
                        .WithMany("Assignments")
                        .HasForeignKey("TAuId");
                });

            modelBuilder.Entity("OnlineHelpSystem.Models.Exercise", b =>
                {
                    b.HasOne("OnlineHelpSystem.Models.Student", "Student")
                        .WithMany("Exercises")
                        .HasForeignKey("AuId");

                    b.HasOne("OnlineHelpSystem.Models.Course", "Course")
                        .WithMany("Exercises")
                        .HasForeignKey("CourseId");

                    b.HasOne("OnlineHelpSystem.Models.Teacher", "Teacher")
                        .WithMany("Exercises")
                        .HasForeignKey("TAuId");
                });

            modelBuilder.Entity("OnlineHelpSystem.Models.StudentAssignment", b =>
                {
                    b.HasOne("OnlineHelpSystem.Models.Assignment", "Assignment")
                        .WithMany("StudentAssignments")
                        .HasForeignKey("AssignmentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineHelpSystem.Models.Student", "Student")
                        .WithMany("StudentAssignments")
                        .HasForeignKey("AuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineHelpSystem.Models.StudentCourse", b =>
                {
                    b.HasOne("OnlineHelpSystem.Models.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("AuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineHelpSystem.Models.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineHelpSystem.Models.Teacher", b =>
                {
                    b.HasOne("OnlineHelpSystem.Models.Course", "Course")
                        .WithMany("Teachers")
                        .HasForeignKey("CourseId");
                });
#pragma warning restore 612, 618
        }
    }
}
